### ISSUE TITLE
Odskakuje hlavička

### ISSUE THREAD

**Issue by petrlizal** [literat/dsw-oddil-wp-theme#24]
combined.min

Odskakuje hlavička pokud roz-kliknete rubriky oproti sekci stránky..  

špatně
.archive {
  display: block;
  padding-top: 50px;
  padding-bottom: 50px;
}

Dobře
.archive {
  display: block;
  padding-top: 0px;
  padding-bottom: 50px;
}

**Comment by literat** [comment]
This issue was moved to skaut/dsw-oddil#27
